### ISSUE TITLE
neuprint_find_neurons("EB") returns error

### ISSUE THREAD

**Issue by bkhulse** [natverse/neuprintr#18]
Calling neuprint_find_neurons("EB") returns this error: 

Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match

It looks like this started happening when they added the sub ROIs to the EB (eg EBr3pw). neuprint_find_neurons can return data on the sub ROIs though, just not "EB".

**Comment by romainFr** [comment]
Have you updated since yesterday? This is fixed by #14 (sorry the pace of updates is a bit fast those days), at least it works on my machine. Let me know if updating fixes it for you too.

**Comment by hjmh** [comment]
True, it seems to work. Sorry, I forgot to restart R after updating and thought that this was still an issue.
